src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Program\Program;
use App\Entity\Traits\IdTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    use IdTrait;

    public const ROLE_ADMIN = 'ROLE_ADMIN';
    public const ROLE_USER = 'ROLE_USER';
    public const ROLE_PROVIDER = 'ROLE_PROVIDER';
    public const ROLE_SEO_MANAGER = 'ROLE_SEO_MANAGER';
    public const ROLE_REDACTOR = 'ROLE_REDACTOR';

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    protected string $email;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    protected bool $active = false;

    /**
     * @ORM\Column(type="json")
     */
    protected array $roles = [];

    /**
     * @ORM\Column(type="string")
     */
    protected ?string $password;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected ?string $socialKey;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\UserInfo", mappedBy="user", cascade={"persist", "remove"})
     */
    protected ?UserInfo $userInfo = null;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Provider", mappedBy="user", cascade={"persist", "remove"})
     */
    protected ?Provider $provider;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Program\ProgramReview", mappedBy="user", fetch="LAZY")
     */
    protected Collection $programReviews;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Program\ProgramRequest", mappedBy="user", fetch="LAZY")
     */
    protected Collection $programRequests;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Program\ProgramQuestion", mappedBy="user", fetch="LAZY")
     */
    protected Collection $programQuestions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ChatMessage", mappedBy="user")
     */
    protected Collection $sentChatMessages;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ChatMessage", mappedBy="recipient")
     */
    protected Collection $receivedChatMessages;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Provider", inversedBy="favoriteUsers", fetch="LAZY")
     */
    protected Collection $favoriteProviders;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Program\Program", inversedBy="favoriteUsers", fetch="LAZY")
     */
    protected Collection $favoritePrograms;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Article", inversedBy="favoriteUsers", fetch="LAZY")
     */
    protected Collection $favoriteArticles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Service\AbstractService", mappedBy="user", fetch="LAZY")
     */
    protected Collection $services;

    public function __construct()
    {
        $this->favoriteProviders = new ArrayCollection();
        $this->favoritePrograms = new ArrayCollection();
        $this->favoriteArticles = new ArrayCollection();
        $this->programReviews = new ArrayCollection();
        $this->programRequests = new ArrayCollection();
        $this->programQuestions = new ArrayCollection();
        $this->sentChatMessages = new ArrayCollection();
        $this->receivedChatMessages = new ArrayCollection();
        $this->services = new ArrayCollection();
    }

    public function getUsername(): string
    {
        return $this->email;
    }

    public function setUsername(string $username): self
    {
        $this->email = $username;
        return $this;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;
        return $this;
    }

    public function isActive(): bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;
        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }

    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;
        return $this;
    }

    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getSocialKey(): ?string
    {
        return $this->socialKey;
    }

    public function setSocialKey(?string $socialKey): self
    {
        $this->socialKey = $socialKey;
        return $this;
    }

    public function getUserInfo(): ?UserInfo
    {
        return $this->userInfo;
    }

    public function setUserInfo(UserInfo $userInfo): self
    {
        $this->userInfo = $userInfo;
        return $this;
    }

    public function getProvider(): ?Provider
    {
        return $this->provider;
    }

    public function setProvider(?Provider $provider): self
    {
        $this->provider = $provider;
        return $this;
    }

    public function getFavoriteProviders(): Collection
    {
        return $this->favoriteProviders;
    }

    public function setFavoriteProviders(Collection $favoriteProviders): self
    {
        $this->favoriteProviders = $favoriteProviders;
        return $this;
    }

    public function addFavoriteProvider(Provider $favoriteProvider): self
    {
        $this->favoriteProviders->add($favoriteProvider);
        return $this;
    }

    public function getFavoritePrograms(): Collection
    {
        return $this->favoritePrograms;
    }

    public function setFavoritePrograms(Collection $favoritePrograms): self
    {
        $this->favoritePrograms = $favoritePrograms;
        return $this;
    }

    public function addFavoriteProgram(Program $favoriteProgram): self
    {
        $this->favoritePrograms->add($favoriteProgram);
        return $this;
    }

    public function getFavoriteArticles(): Collection
    {
        return $this->favoriteArticles;
    }

    public function setFavoriteArticles(Collection $favoriteArticles): self
    {
        $this->favoriteArticles = $favoriteArticles;
        return $this;
    }

    public function addFavoriteArticle(Article $article): self
    {
        $this->favoriteArticles->add($article);
        return $this;
    }

    public function getFavoriteCount(): int
    {
        return
            $this->getFavoriteProviders()->count() +
            $this->getFavoritePrograms()->count() +
            $this->getFavoriteArticles()->count();
    }

    public function getProgramReviews()
    {
        return $this->programReviews;
    }

    public function setProgramReviews($programReviews): self
    {
        $this->programReviews = $programReviews;
        return $this;
    }

    public function getProgramRequests()
    {
        return $this->programRequests;
    }

    public function setProgramRequests($programRequests): self
    {
        $this->programRequests = $programRequests;
        return $this;
    }

    public function getProgramQuestions()
    {
        return $this->programQuestions;
    }

    public function setProgramQuestions($programQuestions): self
    {
        $this->programQuestions = $programQuestions;
        return $this;
    }

    public function isProvider(): bool
    {
        return in_array(self::ROLE_PROVIDER, $this->getRoles(), true);
    }
}

templates/components/header/blocks/categories.html.twig
<nav class="scroll-block dropdown categories-menu">
  <div class="menu-container">
    <span class="back-drop">
      <i class="icon-left"></i>
    </span>
    <span class="close-drop">
      <i class="icon-cancel"></i>
    </span>

    <ul class="dropdown__menu">
      {% for menuItem in getMenuItems() %}
        <li class="dropdown__menu-item">
          <a class="main-category-link" href="{{ path('app.search', {category: menuItem.id}) }}">
            {{ menuItem.name }}
          </a>
          <span class="dropdown__menu-icon"></span>
          <ul class="dropdown__right">
            {% for childMenuItem in menuItem.childCategories %}
              <li>
                <a href="{{ path('app.search', {category: menuItem.id ,subcategory: childMenuItem.id}) }}">
                  {{ childMenuItem.name }}
                </a>
              </li>
            {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  </div>
</nav>

templates/components/header/blocks/menu.html.twig
<div class="header__menu">
  <div class="container">
    <ul class="menu {{ app.user is not null and is_granted('ROLE_PROVIDER') ? 'program-add' : '' }}">
      <li class="menu__item">
        <a href="{{ path('faq.provider') }}" class="menu__item-link">Для провайдеров обучения </a>
      </li>
      <li class="menu__item">
        <a href="{{ path('faq.student') }}" class="menu__item-link">Для желающих обучаться</a>
      </li>
      <li class="menu__item">
        <a href="{{ path('program.index') }}" class="menu__item-link">Программы обучения</a>
      </li>
      <li class="menu__item">
        <a href="{{ path('provider.index') }}" class="menu__item-link">Провайдеры обучения</a>
      </li>
      <li class="menu__item">
        <a href="{{ path('blog.index') }}" class="menu__item-link">Блог</a>
      </li>
      {% if app.user is not null and is_granted('ROLE_PROVIDER') %}
        <li class="menu__item">
          <i class="icon-add-folder"></i>
          <a href="{{ path('program.add') }}" class="menu__item-link">
            Добавить программу
          </a>
        </li>
      {% endif %}
    </ul>

    <ul class="menu-mobile">
      <li class="menu-mobile__item {{ app.user is not null and is_granted('ROLE_PROVIDER') ? '' : 'wide' }}">
        <i class="icon-square"></i>
        <a href="#" class="menu-mobile__item-link">
          Меню
        </a>
        <ul class="sub-menu">
          <li class="menu__item">
            <a href="{{ path('faq.provider') }}" class="menu__item-link">Для провайдеров обучения </a>
          </li>
          <li class="menu__item">
            <a href="{{ path('faq.student') }}" class="menu__item-link">Для желающих обучаться</a>
          </li>
          <li class="menu__item">
            <a href="{{ path('program.index') }}" class="menu__item-link">Программы обучения</a>
          </li>
          <li class="menu__item">
            <a href="{{ path('provider.index') }}" class="menu__item-link">Провайдеры обучения</a>
          </li>
          <li class="menu__item">
            <a href="{{ path('blog.index') }}" class="menu__item-link">Блог</a>
          </li>
        </ul>
      </li>
      {% if app.user is not null and is_granted('ROLE_PROVIDER') %}
        <li class="menu-mobile__item">
          <i class="icon-add-folder"></i>
          <a href="{{ path('program.add') }}" class="menu-mobile__item-link">
            Добавить программу
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</div>

templates/components/header/blocks/provider.dropdown.html.twig
{% set messagesCount =  getNewMessagesCount(app.user) %}

<ul>
  <li>
    <i class="icon-gear"></i>
    <a  class="header-dropdown-link" href="{{ path('site.profile', { path: 'settings' }) }}">Настройки профиля</a>
  </li>
  <li>
    <i class="icon-web-development"></i>
    <a  class="header-dropdown-link" href="{{ path('site.profile', { path: 'programs' }) }}">Программы обучения</a>
  </li>
  <li>
    <i class="icon-contract"></i>
    <a class="header-dropdown-link" href="{{ path('site.profile', { path: 'publications' }) }}">Публикации</a>
  </li>
  <li>
    <i class="icon-email1"></i>
    <a  class="header-dropdown-link" href="{{ path('site.profile', { path: 'messages' }) }}">
      Сообщения <span class="header-notification-count notification {{ messagesCount > 0 ? 'active' : '' }}">{{ messagesCount }}</span>
    </a>
  </li>
  <li>
    <i class="icon-google"></i>
    <a class="header-dropdown-link" href="{{ path('site.profile', { path: 'payments' }) }}">Платные услуги, документы</a>
  </li>
  <li>
    <i class="icon-out"></i>
    <div class="header-dropdown-link logout-link">Выйти</div>
  </li>
</ul>

templates/components/header/blocks/top.html.twig
<div class="header__top">
  <div class="container header__top_container">
    <div class="logo-mobile">
      <a href="{{ path('site.index') }}">
        <img src="/img/logo_mobile.png" alt="">
      </a>
    </div>

    <div class="header__top-left">
      <div class="logo-container">
        <a href="{{ path('site.index') }}">
          <img class="logo-img" src="/img/svg/logo.svg" alt="logo">
        </a>
      </div>

      <div class="button__menu categories-menu-btn">
        <div class="open-drop d-flex">
            <span class="button__menu-icon">
              <i class="icon-menu"></i>
            </span>
          <span class="button__menu-text">Категории</span>
        </div>
        {% include 'components/header/blocks/categories.html.twig' %}
      </div>

      <div class="open-change-city button-container">
        <div class="button-icon open-city-selector-modal-btn">
          <i class="icon-place"></i>
        </div>
        <div class="button-info">
          <span class="button-text">Ваш город:</span>
          <span class="button-link open-city-selector-modal-btn">{{ getCurrentLocation() }}</span>
        </div>
      </div>
    </div>

    <div class="header__top-right">
      {% if app.user is not null %}
        <div class="header__top-right">
          <div class="button-container heart">
            <a href="{{ path('app.favorite') }}">
              <div class="button-icon">
                <i class="icon-heart"></i>
                <span class="button-notification user-favorite-count">{{ app.user.favoriteCount }}</span>
              </div>
            </a>
          </div>
          <div class="button-container">
            <a href="{{ path('app.compare') }}">
              <div class="button-icon">
                <i class="icon-add-file"></i>
                <span class="button-notification compare-count">{{ getCompareCount(app.request.cookies) }}</span>
              </div>
            </a>
          </div>
          <div class="button-container auth">
            <div class="button-icon open-header-dropdown-btn">
              <i class="icon-login"></i>
            </div>
            <div class="button-info auth-text open-header-dropdown-btn">
              <span class="button-text">Добро пожаловать,</span>
              <span class="button-text">{{ getUsername(app.user) }}</span>
            </div>
            <div class="dropdown header-dropdown">
              {% if is_granted('ROLE_PROVIDER') %}
                {% include 'components/header/blocks/provider.dropdown.html.twig' %}
              {% else %}
                {% include 'components/header/blocks/user.dropdown.html.twig' %}
              {% endif %}
            </div>
          </div>
        </div>
      {% else %}
        <div class="button-container">
          <a href="{{ path('app.compare') }}">
            <div class="button-icon">
              <i class="icon-add-file"></i>
              <span class="button-notification compare-count">{{ getCompareCount(app.request.cookies) }}</span>
            </div>
          </a>
        </div>
        <div class="button-container">
          <div class="open-auth button-icon open-login-modal-btn">
            <i class="icon-arrow"></i>
          </div>
          <div class="button-info auth">
            <span class="open-auth button-text open-login-modal-btn">Вход</span>
            <span class="open-type-account button-text open-register-modal-btn">Регистрация</span>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
</div>

templates/components/header/blocks/user.dropdown.html.twig
{% set messagesCount =  getNewMessagesCount(app.user) %}

<ul>
  <li>
    <i class="icon-gear"></i>
    <a class="header-dropdown-link" href="{{ path('site.profile', { path: 'settings' }) }}">Настройки профиля</a>
  </li>
  <li>
    <i class="icon-email1"></i>
    <a class="header-dropdown-link" href="{{ path('site.profile', { path: 'messages' }) }}">
      Сообщения <span class="header-notification-count notification {{ messagesCount > 0 ? 'active' : '' }}">{{ messagesCount }}</span>
    </a>
  </li>
  <li>
    <i class="icon-student"></i>
    <a class="header-dropdown-link" href="{{ path('site.profile', { path: 'learn' }) }}">Мое обучения</a>
  </li>
  <li>
    <i class="icon-out"></i>
    <div class="header-dropdown-link logout-link">Выйти</div>
  </li>
</ul>