src/Entity/Upload.php
<?php

namespace App\Entity;

use App\Entity\Traits\IdTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class Upload
{
    use IdTrait;

    public const UPLOAD_PATH = '/upload';

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected string $name;

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getPublicPath(): string
    {
        $parts = explode('-', $this->getName());

        return sprintf('%s/%s/%s/%s/%s',
            self::UPLOAD_PATH,
            substr($parts[0], 0, 3),
            substr($parts[1], 0, 3),
            substr($parts[2], 0, 3),
            $this->getName()
        );
    }
}

src/Controller/Admin/ProviderController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Category;
use App\Entity\Provider;
use App\Entity\ProviderRequisites;
use App\Helpers\SearchHelper;
use App\Repository\CategoryRepository;
use App\Repository\LocationRepository;
use App\Repository\ProviderRepository;
use App\Repository\ProviderRequisitesRepository;
use App\Service\UploadServiceInterface;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/api/admin/provider")
 */
class ProviderController extends AbstractController
{
    protected EntityManagerInterface $entityManager;
    protected CategoryRepository $categoryRepository;
    protected ProviderRepository $providerRepository;
    protected ProviderRequisitesRepository $providerRequisitesRepository;
    protected LocationRepository $locationRepository;
    protected UploadServiceInterface $uploadService;

    public function __construct(
        EntityManagerInterface $entityManager,
        CategoryRepository $categoryRepository,
        ProviderRepository $providerRepository,
        ProviderRequisitesRepository $providerRequisitesRepository,
        LocationRepository $locationRepository,
        UploadServiceInterface $uploadService
    ) {
        $this->entityManager = $entityManager;
        $this->categoryRepository = $categoryRepository;
        $this->providerRepository = $providerRepository;
        $this->providerRequisitesRepository = $providerRequisitesRepository;
        $this->locationRepository = $locationRepository;
        $this->uploadService = $uploadService;
    }

    /**
     * @Route("", name="admin.provider.index", methods={"GET"})
     *
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function index(Request $request): Response
    {
        $searchQuery = SearchHelper::createFromRequest($request, [Provider::class]);

        $paginator = $this->providerRepository->getPaginatorResult($searchQuery);

        $items = [];
        foreach ($paginator->getItems() as $item) {
            $items[] = $this->prepareItem($item);
        }

        return new JsonResponse([
            'total_pages' => $paginator->getTotalPageCount(),
            'current_page' => $paginator->getCurrentPage(),
            'items' => $items,
        ]);
    }

    public function prepareItem(Provider $item): array
    {
        return [
            'id' => $item->getId(),
            'name' => $item->getName(),
            'image' => $item->getImage() ? $item->getImage()->getPublicPath() : null,
        ];
    }

    /**
     * @Route("/{provider}", name="admin.provider.view", methods={"GET"}, requirements={"provider"="[0-9]+"})
     */
    public function view(Provider $provider): Response
    {
        try {
            $categories = [];

            /** @var Category $category */
            foreach ($provider->getCategories() as $category) {
                $categories[] = [
                    'id' => $category->getId(),
                    'name' => $category->getName(),
                    'sort' => $category->getSort(),
                ];
            }

            $data = [
                'id' => $provider->getId(),
                'name' => $provider->getName(),
                'description' => $provider->getDescription(),
                'image' => $provider->getImage() ? $provider->getImage()->getPublicPath() : null,
                'categories' => $categories,
                'location' => $provider->getLocation() ? $provider->getLocation()->getId() : null,
                'balance' => $provider->getBalance(),
            ];

            if ($providerRequisites = $this->providerRequisitesRepository->findProviderRequisitesByProvider($provider)) {
                $data = array_merge($data, [
                    'organizationName' => $providerRequisites->getOrganizationName() ?: '',
                    'legalAddress' => $providerRequisites->getLegalAddress() ?: '',
                    'mailingAddress' => $providerRequisites->getMailingAddress() ?: '',
                    'ITN' => $providerRequisites->getITN() ?: '',
                    'IEC' => $providerRequisites->getIEC() ?: '',
                    'PSRN' => $providerRequisites->getPSRN() ?: '',
                    'OKPO' => $providerRequisites->getOKPO() ?: '',
                    'checkingAccount' => $providerRequisites->getCheckingAccount() ?: '',
                    'correspondentAccount' => $providerRequisites->getCorrespondentAccount() ?: '',
                    'BIC' => $providerRequisites->getBIC() ?: '',
                    'bank' => $providerRequisites->getBank() ?: '',
                ]);
            }

            return new JsonResponse($data);
        } catch (Exception $e) {
            return new JsonResponse([], 404);
        }
    }

    /**
     * @Route("", name="admin.provider.create", methods={"POST"})
     */
    public function create(Request $request): Response
    {
        try {
            $provider = new Provider();
            $this->setProviderFieldsFromRequest($provider, $request);

            /** @var UploadedFile $uploadImage */
            if ($uploadImage = $request->files->get('uploadImage')) {
                $providerImage = $this->uploadService->createUpload($uploadImage);

                $provider->setImage($providerImage);

                $this->entityManager->persist($providerImage);
            }

            $providerRequisites = (new ProviderRequisites())->setProvider($provider);
            $this->setProviderRequisitesFieldsFromRequest($providerRequisites, $request);

            $this->entityManager->persist($providerRequisites);
            $this->entityManager->persist($provider);
            $this->entityManager->flush();

            return new JsonResponse([]);
        } catch (Exception $e) {
            return new JsonResponse(['message' => $e->getMessage()], 400);
        }
    }

    /**
     * @Route("", name="admin.provider.update", methods={"PUT"})
     */
    public function update(Request $request): Response
    {
        /** @var Provider $provider */
        $provider = $this->providerRepository->find($request->get('id'));

        if ($provider === null) {
            return new JsonResponse([], 404);
        }

        $this->setProviderFieldsFromRequest($provider, $request);

        $providerRequisites = $this->providerRequisitesRepository->findProviderRequisitesByProvider($provider);

        if ($providerRequisites === null) {
            $providerRequisites = (new ProviderRequisites())->setProvider($provider);
        }

        $this->setProviderRequisitesFieldsFromRequest($providerRequisites, $request);

        try {
            /** @var UploadedFile $uploadImage */
            $uploadImage = $request->files->get('uploadImage');

            if ($uploadImage || $request->get('image') === 'null') {
                $oldImage = $provider->getImage();
                if ($oldImage !== null) {
                    $provider->setImage(null);
                    $this->uploadService->deleteUpload($oldImage);
                }
            }

            if ($uploadImage) {
                $uploadImage = $this->uploadService->createTestUpload($uploadImage);
                $providerImage = $this->uploadService->createUpload($uploadImage);
                $provider->setImage($providerImage);

                $this->entityManager->persist($providerImage);
            }

            $this->entityManager->persist($provider);
            $this->entityManager->persist($providerRequisites);
            $this->entityManager->flush();

            return new JsonResponse();
        } catch (Exception $e) {
            return new JsonResponse(['message' => $e->getMessage()], 400);
        }
    }

    protected function setProviderFieldsFromRequest(Provider $provider, Request $request): void
    {
        $provider
            ->setName($request->get('name'))
            ->setDescription($request->get('description'))
            ->setBalance($request->get('balance'))
            ->setCategories($this->categoryRepository->findBy(['id' => $request->get('categories')]))
            ->setLocation($this->locationRepository->findOneBy(['id' => $request->get('location')]));
    }

    protected function setProviderRequisitesFieldsFromRequest(ProviderRequisites $providerRequisites, Request $request): void
    {
        $providerRequisites
            ->setOrganizationName($request->get('organizationName'))
            ->setLegalAddress($request->get('legalAddress'))
            ->setMailingAddress($request->get('mailingAddress'))
            ->setITN($request->get('ITN'))
            ->setIEC($request->get('IEC'))
            ->setPSRN($request->get('PSRN'))
            ->setOKPO($request->get('OKPO'))
            ->setCheckingAccount($request->get('checkingAccount'))
            ->setCorrespondentAccount($request->get('correspondentAccount'))
            ->setBIC($request->get('BIC'))
            ->setBank($request->get('bank'));
    }

    /**
     * @Route("", name="admin.provider.delete", methods={"DELETE"})
     */
    public function delete(Request $request): Response
    {
        /** @var Provider $provider */
        $provider = $this->providerRepository->find($request->get('id'));

        if ($provider === null) {
            return new JsonResponse([], 404);
        }

        if ($provider->getImage()) {
            $this->uploadService->deleteUpload($provider->getImage());
        }

        if ($providerRequisites = $this->providerRequisitesRepository->findProviderRequisitesByProvider($provider)) {

src/Controller/ProviderController.php
<?php

namespace App\Controller;

use App\Controller\Traits\SeoTrait;
use App\Entity\Program\Program;
use App\Entity\Program\ProgramGallery;
use App\Entity\Provider;
use App\Enum\PagesKeys;
use App\Repository\CategoryRepository;
use App\Repository\Content\Seo\DefaultSeoRepository;
use App\Repository\ProgramRepository;
use App\Repository\ProviderRepository;
use App\Service\SearchService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/provider")
 */
class ProviderController extends BaseCatalogController
{
    protected const PAGE_ITEM_COUNT = 10;

    use SeoTrait;

    protected ProviderRepository $providerRepository;
    protected ProgramRepository $programRepository;

    public function __construct(
        ProviderRepository $providerRepository,
        ProgramRepository $programRepository,
        CategoryRepository $categoryRepository,
        DefaultSeoRepository $defaultSeoRepository,
        SearchService $searchService
    ) {
        $this->providerRepository = $providerRepository;
        $this->programRepository = $programRepository;
        $this->categoryRepository = $categoryRepository;
        $this->searchService = $searchService;

        $this->setDefaultSeoRepository($defaultSeoRepository);
    }

    /**
     * @Route("", name="provider.index", methods={"GET"})
     */
    public function index(Request $request): Response
    {
        $page = $this->getPageFromRequest($request);

        $searchResult = $this->getProviderSearchResult($request, $page);

        $providers = $this->providerRepository->findBy(['id' => $searchResult['ids']]);

        $favoriteProviderIds = [];

        if ($this->getUser()) {
            foreach ($this->getUser()->getFavoriteProviders() as $provider) {
                $favoriteProviderIds[] = $provider->getId();
            }
        }

        return $this->render('provider/index.html.twig', $this->applySeoToDefaultPage([
            'providers' => $providers,
            'page' => $page,
            'total_pages' => $searchResult['total_pages'],
            'favorite_provider_ids' => $favoriteProviderIds,
        ], PagesKeys::PROVIDER_INDEX_PAGE_SLUG));
    }

    /**
     * @Route("/{provider}", name="provider.view", methods={"GET"})
     */
    public function view(Provider $provider, Request $request): Response
    {
        $searchResult = $this->getProgramSearchResult($request, 0, [$provider->getId()]);
        $programs = $this->programRepository->findBy(['id' => $searchResult['ids']]);

        $gallery = [];

        foreach ($programs as $program) {
            /** @var ProgramGallery $programGallery */
            foreach ($program->getGallery() as $programGallery) {
                $gallery[] = $programGallery;
            }
        }

        return $this->render('provider/view.html.twig', $this->applySeoToProvider([
            'programs' => $programs,
            'gallery' => $gallery,
            'provider' => $provider,
        ], $provider));
    }
}

templates/provider/card-provider.html.twig
<div class="card-catalog">
  <div class="card-catalog-header">
    <div class="logo-company">
      {% if provider.image is not null %}
        <img src="{{ provider.image.publicPath }}" alt="{{ provider.name }}">
      {% else %}
        <img src="/img/provider_no_logo.png" alt="{{ provider.name }}">
      {% endif %}
    </div>
    <div class="title">
      <a href="{{ path('provider.view', { provider: provider.id }) }}">{{ provider.name }}</a>
    </div>
  </div>
  <div class="card-catalog-content">
    {% if provider.description|length > 300 %}
      <p class="text">{{ provider.description|slice(0, 300) }} ...</p>
    {% else %}
      <p class="text">{{ provider.description }}</p>
    {% endif %}
  </div>
  <div class="card-catalog-footer">
    <div class="category">
      {% if provider.categories|length > 0 %}
        <span>Категории:</span>
        {% for category in provider.categories %}
          <a href="#">{{ category.name }}</a>
        {% endfor %}
      {% endif %}
    </div>
    <div class="send">
      {% if app.user is null or not is_granted('ROLE_PROVIDER') %}
        {% if provider.user is not null %}
          <div class="send-email send-message-button" data-user-id="{{ provider.user.id }}">
            <span class="icon email-f"></span>
            Написать
          </div>
        {% endif %}
      {% endif %}
      <div class="add-provider-favorites {{ provider.id in favorite_provider_ids  ? 'active' : '' }}"
           data-id="{{ provider.id }}">
        <i class="icon-love"></i>
        <span>В избранное</span>
      </div>
    </div>
  </div>
</div>

templates/provider/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block stylesheets %}
  {{ parent() }}
  {{ encore_entry_link_tags('provider.index') }}
{% endblock %}

{% set title = 'Каталог провайдеров обучения' %}

{% block body %}
  <div class="main-catalog mt-0">
    <h2 class="title">{{ title }}</h2>
    <div class="box">
      <div class="box-content">
        {% if providers|length < 1 %}
          По вашему запросу ничего не найдено
        {% endif %}
        {% for provider in providers %}
          {% include 'provider/card-provider.html.twig' with {
            provider: provider,
            favorite_provider_ids: favorite_provider_ids
          } %}
        {% endfor %}
      </div>
      <div class="box-sidebar">
        {% include 'provider/blocks/filter.html.twig' %}
      </div>
    </div>

    {% include 'components/paginator.html.twig' with {
      page: page,
      total_pages: total_pages,
      path_name: 'provider.index'
    } %}
  </div>
{% endblock %}

{% block modals %}
  {{ parent() }}
  {% include 'provider/modals.html.twig' %}
{% endblock %}

{% block javascripts %}
  {{ parent() }}
  {{ encore_entry_script_tags('provider.index') }}
{% endblock %}

templates/provider/modals.html.twig
{% include 'components/modals/add.favorite.html.twig' %}

<div id="send-message-modal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <div class="content pb-20">
      <p>Возможность переписки
        с провайдером обучения доступна только авторизованным пользователям
      </p>
      <p>Войдите или зарегистрируйтесь</p>
      <button class="button-blue login-btn">Войти</button>
      <button class="button-red register-btn">Зарегистрироваться</button>
    </div>
  </div>
</div>

<div id="send-new-message-modal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <div class="content pb-20">
      <h4>Написать сообщение</h4>
      <span class="modal-error"></span>
      <textarea class="textarea" placeholder="Введите тест сообщения" cols="30" rows="5" name="message"></textarea>
      <button class="button-blue login-btn">Отправить</button>
    </div>
  </div>
</div>

templates/provider/view.html.twig
{% extends 'layouts/base.html.twig' %}

{% block stylesheets %}
  {{ parent() }}
  {{ encore_entry_link_tags('provider.view') }}
{% endblock %}

{% set title = provider.name %}

{% set additionalBreadcrumb = {
  link: path('provider.index'),
  name: 'Каталог провайдеров обучения'
} %}

{% set categories = providerCategories(provider) %}

{% block body %}
  <div class="main_provider mt-0">
    <div class="container-0 j-c-center">
      <div class="col-lg-10">
        <h2 class="title">{{ title }}</h2>
      </div>
    </div>
    <div class="tab">
      <div class="toggle-menu tab__nav">
        <ul class="nav">
          <li class="toggle-item nav-item nav-item-description {{ (app.request.get('tab') != 'programs' and app.request.get('tab') != 'gallery') ? 'active' : '' }}">
            <i class="icon-gear"></i>Описание провайдера
          </li>
          <li class="toggle-item nav-item nav-item-programs {{ app.request.get('tab') == 'programs' ? 'active' : '' }}">
            <i class="icon-web-development"></i>Программы обучения
          </li>
          <li class="toggle-item nav-item nav-item-gallery {{ app.request.get('tab') == 'gallery' ? 'active' : '' }}">
            <i class="icon-web-development"></i>Фотогалерея
          </li>
        </ul>
        <i class="icon-down-arrow"></i>
      </div>
      <div class="tab__content">
        <div class="tab__content-item tab-description {{ (app.request.get('tab') != 'programs' and app.request.get('tab') != 'gallery') ? 'active' : '' }}">
          <div class="container-0">
            <div class="col-lg-2 col-sm-4 no-gutter">
              <div class="logo-company">
                {% if provider.image is not null %}
                  <img src="{{ provider.image.publicPath }}" alt="{{ provider.name }}">
                {% else %}
                  <img src="/img/provider_no_logo.png" alt="{{ provider.name }}">
                {% endif %}              </div>
              <div class="description">
                Вы владелец или увидели ошибку?
                <span class="feedback-form-modal-btn">
                    Сообщите нам,
                    нажав Ctrl+Enter
                  </span>
              </div>
            </div>
            <div class="col-lg-7 col-sm-4">
              <div class="content">
                <h4 class="result-title">Об учебном заведении</h4>
                <p>{{ provider.description }}</p>

                {% if categories.main|length > 0 %}
                  <h4 class="result-title">Основные категории</h4>
                  {% set i = 0 %}
                  {% for category in categories.main %}
                    {% set i = i + 1 %}
                    <p class="blue">
                      <strong>{{ i }}. {{ category.item.name }}</strong>
                    </p>
                    <span class="text">
                           {{ category.childItems|map(item => item.name)|join(' / ') }}
                      </span>
                  {% endfor %}
                {% endif %}

                {% if categories.additional|length > 0 %}
                  <h4 class="result-title">Дополнительные категории</h4>
                  <p class="blue">
                    <strong>1. Архитектура и строительство архитектура</strong>
                  </p>
                  <span class="text">архитектура   /   реставрация   /   строительство   /   урбанистика</span>
                  <p class="blue">
                    <strong>2. Информационные технологииИТ-менеджмент</strong>
                  </p>
                  <span class="text">информационная безопасность   /   программирование   /    системное администрирование   /    телекоммуникации и связь</span>
                  <p class="blue">
                    <strong>3. Природопользование и экологиягеология и разведка полезных ископаемых </strong>
                  </p>
                  <span class="text">гидрометеорология   /   сельское, лесное и водное хозяйство   /   экология и защита окружающей среды</span>
                {% endif %}

              </div>
            </div>
            <div class="col-lg-3 col-sm-4 no-gutter">
              <div class="contact">
                <h5 class="title">Контакты</h5>
                {% if provider.user is not null and provider.user.userInfo is not null and provider.user.userInfo.phone is not null %}
                  <a class="phone" href="tel:{{ ('7' ~ provider.user.userInfo.phone)|format_phone }}">
                    {{ ('7' ~ provider.user.userInfo.phone)|format_phone }}
                  </a>
                {% endif %}
                {% if provider.providerRequisites.mailingAddress is not null %}
                  <a class="email" href="mailto:{{ provider.providerRequisites.mailingAddress }}">
                    <i class="icon-email1"></i>
                    {{ provider.providerRequisites.mailingAddress }}
                  </a>
                {% endif %}
                {% if provider.providerRequisites.legalAddress is not null %}
                  <a class="address"
                     href="https://yandex.ru/maps?{{ {text:provider.providerRequisites.legalAddress }|url_encode }}"
                     target="_blank"
                  >
                    <i class="icon-place"></i>
                    {{ provider.providerRequisites.legalAddress }}
                  </a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <div class="tab__content-item tab-programs {{ app.request.get('tab') == 'programs' ? 'active' : '' }}">
          <div class="box">
            <div class="box-content">
              <div class="container-0">
                <div class="col-lg-12 pl-0">
                  {% if programs|length < 1 %}
                    У данного провайдера нет программ обучения
                  {% endif %}
                  {% for program in programs %}
                    {% include 'program/card-program.html.twig' with {
                      program: program,
                    } %}
                  {% endfor %}
                </div>
              </div>
            </div>
            <div class="box-sidebar">
              {% include 'program/catalog-filter.html.twig' with { resetPath: path('provider.view', {
                provider: provider.id,
                tab: 'programs'
              }) } %}
            </div>
          </div>
        </div>
        <div class="tab__content-item tab-gallery {{ app.request.get('tab') == 'gallery' ? 'active' : '' }}">
          <div class="box">
            {% if gallery|length < 1 %}
              Фоторграфии с мероприятий отсутсвтуют
            {% endif %}
            {% for galleryItem in gallery %}
              <div class="box-block">
                <div class="photo">
                  <img src="{{ galleryItem.image.publicPath }}" alt="">
                </div>
                <p class="text--center">
                  {{ galleryItem.name }}
                </p>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block javascripts %}
  {{ parent() }}
  {{ encore_entry_script_tags('provider.view') }}
{% endblock %}